import { Router, type IRouter } from "express";
import healthRouter from "./health";
import projectsRouter from "./projects";
import eventsRouter from "./events";
import sessionsRouter from "./sessions";
import analyticsRouter from "./analytics";
import experimentsRouter from "./experiments";
import logsRouter from "./logs";
import requestsRouter from "./requests";
import datastoreRouter from "./datastore";
import funnelsRouter from "./funnels";
import dashboardsRouter from "./dashboards";
import revenueRouter from "./revenue";
import customersRouter from "./customers";
import featureFlagsRouter from "./feature_flags";
import abacatePayRouter from "./abacatepay";
import insightsRouter from "./insights";
import terminalRouter from "./terminal";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/projects", projectsRouter);
router.use("/projects/:projectId/events", eventsRouter);
router.use("/projects/:projectId/sessions", sessionsRouter);
router.use("/projects/:projectId/analytics", analyticsRouter);
router.use("/projects/:projectId/experiments", experimentsRouter);
router.use("/projects/:projectId/logs", logsRouter);
router.use("/projects/:projectId/requests", requestsRouter);
router.use("/projects/:projectId/datastore", datastoreRouter);
router.use("/projects/:projectId/funnels", funnelsRouter);
router.use("/projects/:projectId/dashboards", dashboardsRouter);
router.use("/projects/:projectId/revenue", revenueRouter);
router.use("/projects/:projectId/customers", customersRouter);
router.use("/projects/:projectId/feature-flags", featureFlagsRouter);
router.use("/projects/:projectId/abacatepay", abacatePayRouter);
router.use("/projects/:projectId/insights", insightsRouter);
router.use("/projects/:projectId/terminal", terminalRouter);

export default router;
